# ==================================================
# SOPS encrypted variables file
# ==================================================
# Recursively merges itself with the unencrypted
# variables in this file
# Add this flag when running the playbook:
#   -e sops_file=config.sops.yml
# ==================================================
# Role: dotfiles
# ==================================================
dotfiles_auth_home: ENC[AES256_GCM,data:WoTYGKbmZPgOrXo=,iv:DFhbBx2BA44Lfd5wdO59SxUZkCEAg3E3ygix/ADS2eI=,tag:bAh8KGpxuqEyc6ugT990kw==,type:str]
dotfiles_secrets_src: ENC[AES256_GCM,data:NwJm9akJwp7vqSF+Q3pwLV+BqiDutdGT5w==,iv:+mDLoVDyyWG2bPgN9gM7caCfEEG1CahC+fja9k7M784=,tag:NB8Pk8/GN6jruwd3DqUBrQ==,type:str]
dotfiles_secrets:
    git:
        email: ENC[AES256_GCM,data:fuwU/h30WOfzVPR92pDN+IPKp8690duAEI16pawZnPrwsTye1Aoqnvv/4A==,iv:IhoDgGPOxAt81MVjuJUWHAhZfSiCqlZPuI0VYzMK7Lw=,tag:pz3iapBqcpEEjKPx79KlWg==,type:str]
        signing_key: ENC[AES256_GCM,data:0O4OTIH9FhSaOv1UURTieA==,iv:a2xpktayMo0LH4if7VMiRXOuWDpGyOKppSImbb3lock=,tag:annKbcd5N8dwRFPmrO733A==,type:str]
dotfiles_zsh_extra_aliases:
    cdgit: ENC[AES256_GCM,data:KXjBNC0PuKMsxaZ6Du1T3QH1qPh9B0bCE7ZWpfqj,iv:bFaiJRk2Dc7ZpFT/Z5kD7gCD57+sxf61kl1/8raTqic=,tag:bbQY9eIVsoZtuegED4IH1A==,type:str]
    cddrive: ENC[AES256_GCM,data:6V/9fJh+38mjDA==,iv:nQDbI/YlE/Zyv1LCdlxVr3ZW2asarS7WJrCc36Vey/8=,tag:mq/1tWO1giBB0YLxU665mQ==,type:str]
    rsd: ENC[AES256_GCM,data:1kWxg6ugW9QoCt8LjxM8upPBMPw/hgkVBna/WPttpaEWv+jfZGqKNv8TR+1+cbaEkbpF3RfhVzpVz2vhwMJIBLqnFshfxaRvADG/IOb0hfkFantcJhhd7ysLTAreniobObyC5+DgpSa38GVeYiOaDem94/wFMNfCvJXv5yVOzYsA74HR63s2otEq0cfqHPxMsm2GO56QAVCnjoqCwtlMzZSIgkL0F/8jVYA8rw1cX8RneCUQjnNp9DKTFR5h90piqb+kUJLlOAqchqRfWMDXMeIa9WXlzFbg19LIiRuQR5jgEs2IPfq+DYhhofrjyvYbc6Xx,iv:l9YlVg6paMEbhtqBmrAtq1P3qWD+NevoR78mvWdYMfs=,tag:nXAoti1tXoTSuof1FsAJwg==,type:str]
dotfiles_exclude:
    - agents
# ==================================================
# Role: geerlingguy.mac.homebrew
#   - docs: https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/homebrew/README.md
# ==================================================
homebrew_upgrade_all_packages: true
homebrew_taps:
    - cirruslabs/cli
    - coderabbitai/tap
    - hashicorp/tap
    - teamookla/speedtest
homebrew_installed_packages:
    - age
    - ansible
    - argocd
    - bat
    - bruno-cli
    - cf-terraforming
    - cirruslabs/cli/cirrus
    - cirruslabs/cli/tart
    - cloudflared
    - cmctl
    - coderabbitai/tap/git-gtr
    - etcd
    - exiftool
    - eza
    - ffmpeg
    - fzf
    - gh
    - ghorg
    - git
    - gnupg
    - helm
    - helmfile
    - htop
    - iftop
    - influxdb-cli
    - iperf3
    - jq
    - k9s
    - kind
    - kopia
    - ktop
    - kubectx
    - lazygit
    - make
    - nmap
    - node
    - oci-cli
    - pinentry-mac
    - powerlevel10k
    - rclone
    - ripgrep
    - rsync
    - sops
    - sops
    - stern
    - teamookla/speedtest/speedtest
    - telnet
    - terraform
    - tmux
    - tree
    - velero
    - wakeonlan
    - watch
    - xdg-ninja
    - yq
    - yt-dlp
homebrew_cask_apps:
    - arduino-ide
    - balenaetcher
    - bruno
    - claude
    - claude-code@latest
    - cyberduck
    - datagrip
    - discord
    - docker-desktop
    - drawio
    - firefox
    - google-chrome
    - iterm2
    - keepassxc
    - kopiaui
    - lens
    - logi-options-plus
    - macfuse
    - mqtt-explorer
    - obs
    - obsidian
    - openboardview
    - pycharm
    - raspberry-pi-imager
    - rectangle
    - sigil
    - spotify
    - surfshark
    - tailscale-app
    - teamviewer
    - tor-browser
    - transmission
    - trezor-suite
    - veracrypt
    - visual-studio-code
    - vlc
    - whatsapp
    - yubico-authenticator
    - zoom
# ==================================================
# Role: mas (prefer brew cask when possible)
# ==================================================
mas_upgrade_all_apps: true
mas_installed_apps:
    - name: AmorphousDiskMark
      id: 1168254295
    - name: GeoTag
      id: 1465180184
    - name: Keynote
      id: 409203825
    - name: Microsoft Excel
      id: 462058435
    - name: Microsoft PowerPoint
      id: 462062816
    - name: Microsoft Word
      id: 462054704
    - name: Numbers
      id: 409203825
    - name: Pages
      id: 409201541
    - name: Panorama Stitcher Mini
      id: 1062350226
    - name: Spherical Viewer
      id: 1489700765
    - name: Surfshark
      id: 1437809329
    - name: Trello
      id: 1278508951
    - name: WireGuard
      id: 1451685025
mas_uninstalled_apps:
    - name: GarageBand
      id: 682658836
    - name: iMovie
      id: 408981434
# ==================================================
# Role: python
# ==================================================
python_pyenv_versions:
    - 3.11.14
    - 3.14.2
python_pyenv_global: 3.14.2
python_uv_versions: []
python_uv_tools:
    - ansible
    - black
    - firefly-cli
    - flake8
    - isort
    - mypy
    - pre-commit
    - ruff
    - versioneer
# ==================================================
# Role: java
# ==================================================
java_versions: []
java_jenv_global: []
# ==================================================
# Role: dock
# ==================================================
dockitems_persist:
    - name: iTerm
      path: /Applications/iTerm.app
      pos: 1
    - name: Activity Monitor
      path: /System/Applications/Utilities/Activity Monitor.app
      pos: 2
    - name: Firefox
      path: /Applications/Firefox.app
      pos: 3
    - name: KeePassXC
      path: /Applications/KeePassXC.app
      pos: 4
    - name: Messages
      path: /System/Applications/Messages.app
      pos: 5
    - name: FaceTime
      path: /System/Applications/FaceTime.app
      pos: 6
    - name: WhatsApp
      path: /Applications/WhatsApp.app
      pos: 7
    - name: Calendar
      path: /System/Applications/Calendar.app
      pos: 8
    - name: Reminders
      path: /System/Applications/Reminders.app
      pos: 9
    - name: Stickies
      path: /System/Applications/Stickies.app
      pos: 10
    - name: Obsidian
      path: /Applications/Obsidian.app
      pos: 11
    - name: Spotify
      path: /Applications/Spotify.app
      pos: 12
    - name: Photos
      path: /System/Applications/Photos.app
      pos: 14
    - name: VSCode
      path: /Applications/Visual Studio Code.app
      pos: 15
    - name: PyCharm
      path: /Applications/PyCharm.app
      pos: 16
    - name: Docker
      path: /Applications/Docker.app
      pos: 17
    - name: Bruno
      path: /Applications/Bruno.app
      pos: 18
    - name: Adobe Lightroom Classic
      path: /Applications/Adobe Lightroom Classic/Adobe Lightroom Classic.app
      pos: 19
    - name: Adobe Bridge 2023
      path: /Applications/Adobe Bridge 2023/Adobe Bridge 2023.app
      pos: 20
    - name: System Settings
      path: /System/Applications/System Settings.app
      pos: 21
    - name: Applications
      path: /Applications
      pos: 22
    - name: Downloads
      path: /Users/{{ ansible_env.USER }}/Downloads
      pos: 23
# ==================================================
# Role: macos
# ==================================================
macos_ini_properties:
    # KeePassXC
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: General
      option: AutoReloadOnChange
      value: "false"
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: General
      option: AutoSaveAfterEveryChange
      value: "false"
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: General
      option: AutoSaveNonDataChanges
      value: "false"
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: General
      option: AutoSaveOnExit
      value: "false"
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: General
      option: AutoTypeDelay
      value: 50
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: General
      option: AutoTypeStartDelay
      value: 300
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: General
      option: BackupBeforeSave
      value: "true"
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: General
      option: ConfigVersion
      value: 2
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: General
      option: GlobalAutoTypeKey
      value: 80
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: General
      option: GlobalAutoTypeModifiers
      value: 201326592
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: General
      option: UpdateCheckMessageShown
      value: "true"
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: GUI
      option: TrayIconAppearance
      value: monochrome
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: PasswordGenerator
      option: AdvancedMode
      value: "true"
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: PasswordGenerator
      option: ExcludeAlike
      value: "false"
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: PasswordGenerator
      option: ExcludedChars
      value: '^`~;:'
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: PasswordGenerator
      option: Length
      value: 20
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: PasswordGenerator
      option: Logograms
      value: "true"
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: PasswordGenerator
      option: LowerCase
      value: "true"
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: PasswordGenerator
      option: Math
      value: "true"
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: PasswordGenerator
      option: Type
      value: 0
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: PasswordGenerator
      option: WordCount
      value: 2
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: Security
      option: ClearClipboardTimeout
      value: 60
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: Security
      option: EnableCopyOnDoubleClick
      value: "true"
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: Security
      option: HidePasswordPreviewPanel
      value: "false"
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: Security
      option: IconDownloadFallback
      value: "true"
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: Security
      option: PasswordsHidden
      value: "false"
    - path: $HOME/Library/Application Support/KeePassXC/keepassxc.ini
      section: Security
      option: PasswordsRepeatVisible
      value: "false"
# macos_hosts:
# - {ip: 127.0.0.1, hosts: tst}
# - {ip: 127.0.0.1, hosts: tst2}
# - {ip: 127.0.0.1, hosts: tst3}
# - {ip: 127.0.0.1, hosts: tst4}
macos_add_adobe_hosts: true
# macos_ssh_config:  # Moved to vars/ssh_config.enc.yml
# ==================================================
# Role: ide
# ==================================================
ide_vscode_extensions:
    - anan.jetbrains-darcula-theme
    - anthropic.claude-code
    - github.copilot
    - github.copilot-chat
    - github.vscode-github-actions
    - james-yu.latex-workshop
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-python.debugpy
    - ms-python.python
    - redhat.ansible
    - redhat.vscode-yaml
    - signageos.signageos-vscode-sops
    - vscode-icons-team.vscode-icons
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcWdlcHlpZ0ZaUW5rUENM
            TzFxaGhwT0NKQVhja0d4LzFTOEV5YW9MT1RNCnhzdFFkNkRXcGw0NmRBV3YrVmox
            NGZCZGc5TlROd2pUYy81UGJ3Q3VYUlkKLS0tIEdRL1ovRUFxVFlzRVlOREhDOWV4
            SnlTdzlLSzZ4bEFLQVJ4MHdsYXdtMmMKvEuV/o6iWIFCuR7sXH+WeS3otM4TIza+
            bQmc2qA8bh2EjwhV2IdDw4hWmpjRdmEzneLVTKiaztPRpSyjfVOyNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2g0g2z9jdgnqx826e8d0d78y8z0lc7ngdadm3jw9gzpxj2nf5rs0hm6p6
    encrypted_regex: ^(dotfiles_auth_home|dotfiles_repo|dotfiles_secrets_src|dotfiles_secrets|dotfiles_zsh_extra_aliases)$
    lastmodified: "2026-07-02T23:27:57Z"
    mac: ENC[AES256_GCM,data:eAjiebTDWK3SOaAFmBpDauA8k/lfBPqPbaLg7fY4DJsOx65pFyUlIC4nuA0jrjTj3LP2GzDo3qzt98E7wDsFpzI2T5EMdprJ3jBZ6GL2k/zmKwmCaTDVAlsyu6JML4izaUTAf1nwSD5ZFZ+//owaVfchWY4zYg4RBQTK20/QVnM=,iv:aFLxQ99MS7myngD0HkKh8UYYqgVHiU3U/CL7USSx6Bo=,tag:E6zfqwfIfZexTNP5rd97TA==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
