---
- name: Configure local host
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - config.default.yml

  pre_tasks:
    - name: Python interpreter
      debug: { var: ansible_python_interpreter }
      tags: [always]
    - name: Ensure python3
      assert: { that: ansible_facts.python_version > "2" }
      tags: [always]
    - name: Provision SOPS and variables
      include_role:
        name: sops
        apply: { tags: [always] }
      when: sops_file is defined
      tags: [always]

  roles:
    - { role: elliotweiser.osx-command-line-tools, tags: [install] }
    - { role: dotfiles, tags: [dotfiles] }
    - { role: geerlingguy.mac.homebrew, tags: [brew] }
    - { role: geerlingguy.mac.mas, tags: [mas] }

    - { role: python, tags: [python] }
    - { role: java, tags: [java] }
    # - {role: macos, tags: [macos]}
    - { role: ide, tags: [ide] }

    # - {role: geerlingguy.mac.dock, tags: [dock]}
