---
- name: Configure local host
  hosts: localhost

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: mas
      when: mas_installed_apps
      tags: ['mas']
    - role: python
      tags: ['python']
    - role: geerlingguy.mac.dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/osx.yml
    - import_tasks: tasks/shell.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/git_clone.yml
    - import_tasks: tasks/vscode.yml
