---
- name: Configure local host
  hosts: localhost

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Ensure python3
      assert:
        that: ansible_python_version > "2"

    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: [always]

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: dotfiles
      tags: [dotfiles]
    - role: geerlingguy.mac.homebrew
      tags: [homebrew]
    - role: mas
      when: mas_installed_apps
      tags: [mas]
    - role: python
      tags: [python]
    - role: geerlingguy.mac.dock
      tags: [dock]

  tasks:
    - name: Task OSX
      import_tasks: tasks/osx.yml
      tags: [osx]
    - name: Task Terminal
      import_tasks: tasks/terminal.yml
      tags: [terminal]
    - name: Task Git
      import_tasks: tasks/git.yml
      tags: [git]
    - name: Task Git Clone
      import_tasks: tasks/git_clone.yml
      tags: [git]
    - name: Task VSCode
      import_tasks: tasks/vscode.yml
      tags: [vscode]
