---
- name: Install VSCode extensions
  vars:
    code_bin: "{{ homebrew_cask_appdir | default('/Applications') }}/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code"
  command: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"
  register: code_install
  changed_when:
    - code_install.rc == 0
    - "'successfully installed' in code_install.stdout"
  when: vscode_extensions is defined
