---
- name: "Move dock order: {{ item.name }}"
  shell: |
    set -o pipefail
    {% if item.type | default("") != "" %}
      # Skip spacer
      echo "Item is spacer. Skipping..."
      exit 0;
    {% else %}
      slot_info=$(dockutil --find '{{ item.name }}')
      if [ $? -eq 0 ]; then
        slot_value=$(echo "$slot_info" | grep -o -E 'slot [0-9]+' | awk '{print $2}')
        if [ "$slot_value" != "{{ index + 1 }}" ]; then
            echo "Will move to slot {{ index + 1 }}, currently at $slot_value"
            dockutil --move '{{ item.name }}' --position {{ index + 1 }}
        else
            echo "Slot value is already $slot_value, no action required."
        fi
      else
        echo "Item not found, no action required."
        exit 1;
      fi
    {% endif %}
  register: dockutil_move
  changed_when: dockutil_move.rc == 0 and dockutil_move.stdout_lines[0].startswith("Will move to slot")

- name: Pause for 5 seconds if moved  # noqa no-handler
  pause:
    seconds: 5
  when: dockutil_move.changed
...
