---
- name: Copy configuration files
  become: "{{ item.become | default(false) }}"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0600"
  with_items: "{{ macos_config_files }}"
  when: macos_config_files

- name: Configure /etc/hosts
  become: true
  blockinfile:
    path: /etc/hosts
    block: |
      {% for item in macos_hosts %}
      {{ item.ip }} {{ item.hosts }}
      {% endfor %}
  when: macos_hosts

- name: Add Adobe hosts to /etc/hosts
  when: macos_add_adobe_hosts
  block:
    - name: Download Adobe hosts file
      get_url:
        url: "{{ macos_adobe_hosts_file }}"
        dest: "{{ ansible_env.TMPDIR }}/adobe_hosts.txt"
        mode: "0644"

    - name: Add Adobe hosts file to /etc/hosts
      become: true
      blockinfile:
        path: /etc/hosts
        block: "{{ lookup('file', ansible_env.TMPDIR ~ '/adobe_hosts.txt') }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: BLOCK ADOBE HOSTS"

- name: Configure dock
  block:
    - name: Show recents
      osx_defaults:
        domain: com.apple.dock
        key: show-recents
        type: bool
        value: false
        state: present
    - name: Change icon size
      osx_defaults:
        domain: com.apple.dock
        key: tilesize
        type: float
        value: 30
        state: present
    - name: Dock orientation right
      community.general.osx_defaults:
        domain: com.apple.dock
        key: orientation
        type: string
        value: right
        state: present

- name: Configure trackpad
  block:
    - name: Enable dragging with three finger drag
      community.general.osx_defaults:
        domain: com.apple.AppleMultitouchTrackpad
        key: orienTrackpadThreeFingerDragtation
        type: bool
        value: "true"
        state: present

- name: Configure Menu Bar
  block:
    - name: Set clock
      community.general.osx_defaults:
        domain: com.apple.menuextra.clock
        key: DateFormat
        type: string
        value: '"EEE d MMM HH:mm:ss"'
        state: present
    - name: Flash clock time separators
      community.general.osx_defaults:
        domain: com.apple.menuextra.clock
        key: FlashDateSeparators
        type: bool
        value: "true"
        state: present

- name: Configure Desktop
  block:
    - name: Keep folders on top
      community.general.osx_defaults:
        domain: om.apple.finder
        key: _FXSortFoldersFirstOnDesktop
        type: bool
        value: "true"
        state: present

- name: Restart Dock and Finder
  command: killall Dock && killall Finder
  changed_when: false
