---
- name: Install mas (homebrew)
  homebrew:
    name: mas
    state: present

- name: List installed MAS apps.
  command: mas list
  register: mas_list
  check_mode: false
  changed_when: false

- name: Display MAS installed apps.
  debug:
    var: mas_list.stdout_lines
    verbosity: 1

# Uninstall does not work: https://github.com/mas-cli/mas/issues/313
# - name: Ensure unwanted MAS apps are uninstalled.
#   command: mas uninstall "{{ item.id | default(item) }}"
#   register: mas_uninstall
#   with_items: "{{ mas_uninstalled_apps }}"
#   changed_when:
#     - mas_uninstall.rc == 0
#     - "'==> Installed' in mas_uninstall.stdout_lines[-1]"

- name: Ensure configured MAS apps are installed.
  command: mas install "{{ item.id | default(item) }}"
  register: mas_install
  with_items: "{{ mas_installed_apps }}"
  changed_when:
    - mas_install.rc == 0
    - "'==> Installed' in mas_install.stdout"

- name: Upgrade all apps
  command: mas upgrade
  register: mas_upgrade
  changed_when: "'Warning: Nothing found to upgrade' not in mas_upgrade.stderr"
  when: mas_upgrade_all_apps
