---
- name: Install mas (homebrew)
  homebrew:
    name: mas
    state: present

- name: List installed MAS apps.
  command: mas list
  register: mas_list
  check_mode: false
  changed_when: false

- name: Display MAS installed apps.
  debug:
    var: mas_list.stdout_lines
    verbosity: 0

- name: Ensure unwanted MAS apps are uninstalled.
  command: mas uninstall "{{ item.id|default(item) }}"
  with_items: "{{ mas_uninstalled_apps }}"
  when: (item.id | default(item) | string) in mas_list.stdout

- name: Ensure configured MAS apps are installed.
  command: mas install "{{ item.id|default(item) }}"
  with_items: "{{ mas_installed_apps }}"
  when: (item.id | default(item) | string) not in mas_list.stdout

- name: Upgrade all apps
  command: mas upgrade
  register: mas_upgrade
  changed_when: "'Warning: Nothing found to upgrade' not in mas_upgrade.stderr"
  when: mas_upgrade_all_apps
