---
- name: Create git directory
  file:
    path: "{{ ansible_env.XDG_CONFIG_HOME | default(zshenv.XDG_CONFIG_HOME) | expandvars }}/git"
    state: directory
    mode: "0700"

- name: Create git global config file if not exists
  file:
    path: "{{ ansible_env.XDG_CONFIG_HOME | default(zshenv.XDG_CONFIG_HOME) | expandvars }}/git/config"
    state: touch
    modification_time: preserve
    access_time: preserve
    mode: "0600"

- name: Unset global configs
  git_config:
    scope: global
    name: "{{ item }}"
    state: absent
  with_items: "{{ git_global_absent_configs }}"
  when: git_global_absent_configs

- name: Set global configs
  git_config:
    scope: global
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  when: git_global_present_configs
  loop: "{{ git_global_present_configs }}"

- name: Clone repositories to location if not exist
  git:  # noqa: latest[git]
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    update: false
  with_items: "{{ git_clone_repos }}"
  when: git_clone_repos
