---
name: CI
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:

  integraton-tests:
    name: Integration Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-13, macos-12]

    defaults:
      run:
        shell: zsh {0}

    env:
      ANSIBLE_FORCE_COLOR: '1'
      ANSIBLE_HOME: $HOME/.local/share/ansible

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Uninstall GitHub Actions' built-in Homebrew
        run: curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh | NONINTERACTIVE=1 bash -

      - name: Install dependencies and set environment
        run: |
          sudo pip3 install -r requirements.txt
          ansible-galaxy install -r requirements.yml

      - name: Linting
        run: |
          yamllint .
          ansible-lint

      - name: Test playbook's syntax
        run: ansible-playbook main.yml --syntax-check

      # - name: Playbook dry-run
      #   run: ansible-playbook main.yml --check

      - name: Test playbook with config.default.yml
        run: |
          cp config.default.yml config.yml
          ansible-playbook main.yml

      - name: Test playbook
        run: |
          cp test/config.yml config.yml
          ansible-playbook main.yml --skip-tags dock

      - name: Idempotence check
        run: |
          idempotence=$(mktemp)
          ansible-playbook main.yml --skip-tags dock | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' \
              && (echo 'Idempotence test: pass' && exit 0) \
              || (echo 'Idempotence test: fail' && exit 1)
